version: "3"
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: "mysql" # 容器名称
    restart: always
    ports:
      - "${MYSQL_HOST_PORT}:3306" # 映射端口
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql:rw # 挂载文件夹
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro # 挂载文件夹
    environment:
      - TZ=Asia/Shanghai  # 设置时区
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # 设置mysqlRoot密码
  redis:
    image: redis:${REDIS_VERSION}
    container_name: "redis"
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_DATA_DIR}:/data/:rw
      - ${REDIS_CONF_FILE}:/etc/redis/redis.conf:ro
    command: redis-server /etc/redis/redis.conf
    restart: always
    environment:  # 配置环境变量
      - TZ=Asia/Shanghai  # 设置时区
  # es:
  #   image: elasticsearch:${ES_VERSION}
  #   container_name: "es"
  #   restart: always
  #   expose:
  #     - "9200"
  #   ports:
  #     - "${ES_HOST_PORT}:9200"
  #   volumes:
  #     - ${ES_CONF_FILE}:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  #     - ${ES_DATA_DIR}:/usr/share/elasticsearch/data/:rw
  #     - ${ES_PLUGINS_DIR}:/usr/share/elasticsearch/plugins/:rw
  #     - ${ES_LOG_DIR}:/usr/share/elasticsearch/logs/:rw
  #   environment:  # 配置环境变量
  #     - TZ=Asia/Shanghai  # 设置时区
  #     - discovery.type=single-node
  #     - ES_JAVA_OPTS=-Xms512m -Xmx512m
  php-73:
    build: ./docker/php-73
    container_name: "php-73"
    restart: always
    working_dir: /var/www
    ports:
      - "9000:9000"
    volumes:
      - ${APP_DIR}:/var/www:rw # 挂载项目目录
      - ${PHP72_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro # 挂载配置文件
      - ${PHP72_OPENSSL_FILE}:/usr/local/openssl/cert.pem:ro # 挂载配置文件
    links:
      - "mysql"
      - "redis"
    environment:  # 配置环境变量
      - TZ=Asia/Shanghai  # 设置时区
  php-74:
    build: ./docker/php-74
    container_name: "php-74"
    restart: always
    working_dir: /var/www
    ports:
      - "9001:9000"
    volumes:
      - ${APP_DIR}:/var/www:rw # 挂载项目目录
      - ${PHP72_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro # 挂载配置文件
      - ${PHP72_OPENSSL_FILE}:/usr/local/openssl/cert.pem:ro # 挂载配置文件
    links:
      - "mysql"
      - "redis"
    environment:  # 配置环境变量
      - TZ=Asia/Shanghai  # 设置时区
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: "nginx"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ${APP_DIR}:/var/www:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf/:ro
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    environment:  # 配置环境变量
      - TZ=Asia/Shanghai  # 设置时区
    links:
      - "php-73"
      - "php-74"

